name: Deploy production

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      # TODO: replace with actual subnet IDs (coordianate with DevOps)
      subnet_ids: |
        subnet-0xFD
        subnet-0xFE
        subnet-0xFF
      # TODO: replace with actual security group IDs (coordinate with DevOps)
      security_group_ids: sg-0xFF
      # TODO: Update according to the trigger used
      git_ref: ${{ github.event.workflow_run.head_sha || github.sha }}
    secrets: inherit
