name: Build

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/**'
      - '**.md'
  push:
    branches: [main]

jobs:
  build-test-image-and-run-checks:
    name: Build test image and run checks
    strategy:
      matrix:
        rails_version: [7, 8]
    uses: ./.github/workflows/build-app-image-and-run-checks.yml
    with:
      postgres_version: latest
      postgres_user: postgres
      postgres_password: password
      image_target: ci
      image_tags: rails-template
      image_build_args: |
        RAILS_VERSION: ${{ matrix.rails_version }}
      checks_command: |
        docker run \
          --env DB_HOST=127.0.0.1 \
          --env DB_PORT=5432 \
          --env DB_USERNAME=deploy \
          --env DB_PASSWORD=password \
          --network=host \
          rails-template \
          bin/ci-checks
